[project]
name = "mcpclient"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-groq>=0.3.2",
    "mcp-use>=1.2.5",
    "rich>=14.0.0",
    "streamlit>=1.44.1",
]
